# configs/full_ft.yaml
model:
  model_name: "bert-base-uncased"
  num_labels: 2

data:
  dataset_name: "imdb"
  max_length: 256

training:
  output_dir: "./full_ft_results"
  learning_rate: 2e-5
  per_device_train_batch_size: 8
  num_train_epochs: 3
  fp16: true
  use_wandb: false
